import { Injectable } from '@nestjs/common';

import type { Prisma } from '@reactpulse/database';

import { DatabaseService } from '../database/database.service';

import type { BrowserScanResult } from '../browser/browser.types';

@Injectable()
export class ScanEvidenceService {
  constructor(private readonly database: DatabaseService) {}

  async replaceForScan(
    scanId: string,
    result: BrowserScanResult,
  ): Promise<void> {
    await this.database.client.$transaction(async (tx) => {
      /*
       * A scan may be retried by BullMQ.
       *
       * Evidence is therefore replacement-based:
       *
       * attempt N
       *   ↓
       * remove previous evidence
       *   ↓
       * persist evidence generated by attempt N
       *
       * This prevents duplicate evidence after retries.
       */
      await tx.scanEvidence.deleteMany({
        where: {
          scanId,
        },
      });

      await tx.scanEvidence.create({
        data: {
          scanId,

          type: 'BROWSER',

          sequence: 0,

          data: toJson(result.browser),
        },
      });

      await tx.scanEvidence.create({
        data: {
          scanId,

          type: 'NAVIGATION',

          sequence: 0,

          data: toJson(result.navigation),
        },
      });

      if (result.documentResponse) {
        await tx.scanEvidence.create({
          data: {
            scanId,

            type: 'DOCUMENT_RESPONSE',

            sequence: 0,

            data: toJson(result.documentResponse),
          },
        });
      }

      if (result.network.requests.length > 0) {
        await tx.scanEvidence.createMany({
          data: result.network.requests.map((request) => ({
            scanId,

            type: 'NETWORK_REQUEST' as const,

            sequence: request.sequence,

            data: toJson(request),
          })),
        });
      }

      if (result.network.responses.length > 0) {
        await tx.scanEvidence.createMany({
          data: result.network.responses.map((response) => ({
            scanId,

            type: 'NETWORK_RESPONSE' as const,

            sequence: response.sequence,

            data: toJson(response),
          })),
        });
      }

      if (result.network.failures.length > 0) {
        await tx.scanEvidence.createMany({
          data: result.network.failures.map((failure) => ({
            scanId,

            type: 'NETWORK_FAILURE' as const,

            sequence: failure.sequence,

            data: toJson(failure),
          })),
        });
      }

      if (result.consoleMessages.length > 0) {
        await tx.scanEvidence.createMany({
          data: result.consoleMessages.map((message, index) => ({
            scanId,

            type: 'CONSOLE' as const,

            sequence: index,

            data: toJson(message),
          })),
        });
      }

      await tx.scanEvidence.create({
        data: {
          scanId,

          type: 'PERFORMANCE',

          sequence: 0,

          data: toJson(result.performance.metrics),
        },
      });

      if (result.performance.longTasks.length > 0) {
        await tx.scanEvidence.createMany({
          data: result.performance.longTasks.map((longTask, index) => ({
            scanId,

            type: 'LONG_TASK' as const,

            sequence: index,

            data: toJson(longTask),
          })),
        });
      }
    });
  }
}

function toJson(value: unknown): Prisma.InputJsonValue {
  return value as Prisma.InputJsonValue;
}
